import type { IFriend } from "@/types/friends/friend.types";

export const mock_friends: IFriend[] = [
	{
		id: 1,
		username: "lofi_girl",
		first_name: "Anna",
		last_name: "Lopez",
		avatar: "https://i.pravatar.cc/150?img=32",
		is_following: true,
	},
	{
		id: 2,
		username: "dj_shadow",
		first_name: "David",
		last_name: "Nguyen",
		avatar: "https://i.pravatar.cc/150?img=12",
		is_following: false,
	},
	{
		id: 3,
		username: "rockfan92",
		first_name: "Alex",
		last_name: "Johnson",
		avatar: "https://i.pravatar.cc/150?img=47",
		is_following: true,
	},
	{
		id: 4,
		username: "trapqueen",
		first_name: "Maya",
		last_name: "Rodriguez",
		avatar: "https://i.pravatar.cc/150?img=65",
		is_following: false,
	},
	{
		id: 5,
		username: "jazzman",
		first_name: "Marcus",
		last_name: "Williams",
		avatar: "https://i.pravatar.cc/150?img=24",
		is_following: true,
	},
	{
		id: 6,
		username: "vinyl_lover",
		first_name: "Sophie",
		last_name: "Martinez",
		avatar: "https://i.pravatar.cc/150?img=14",
		is_following: false,
	},
	{
		id: 7,
		username: "beatmakerX",
		first_name: "Liam",
		last_name: "Anderson",
		avatar: "https://i.pravatar.cc/150?img=56",
		is_following: true,
	},
	{
		id: 8,
		username: "house_master",
		first_name: "Nina",
		last_name: "Kowalski",
		avatar: "https://i.pravatar.cc/150?img=9",
		is_following: false,
	},
	{
		id: 9,
		username: "techno_tom",
		first_name: "Tom",
		last_name: "Schneider",
		avatar: "https://i.pravatar.cc/150?img=41",
		is_following: true,
	},
	{
		id: 10,
		username: "salsaqueen",
		first_name: "Isabella",
		last_name: "Garcia",
		avatar: "https://i.pravatar.cc/150?img=18",
		is_following: false,
	},
	{
		id: 11,
		username: "drumline99",
		first_name: "Ethan",
		last_name: "Miller",
		avatar: "https://i.pravatar.cc/150?img=29",
		is_following: true,
	},
	{
		id: 12,
		username: "electro_bae",
		first_name: "Chloe",
		last_name: "Dubois",
		avatar: "https://i.pravatar.cc/150?img=36",
		is_following: false,
	},
	{
		id: 13,
		username: "punky_joe",
		first_name: "Joseph",
		last_name: "Brown",
		avatar: "https://i.pravatar.cc/150?img=7",
		is_following: true,
	},
	{
		id: 14,
		username: "soulvibes",
		first_name: "Amira",
		last_name: "Hassan",
		avatar: "https://i.pravatar.cc/150?img=22",
		is_following: false,
	},
	{
		id: 15,
		username: "indie_rose",
		first_name: "Rose",
		last_name: "Peterson",
		avatar: "https://i.pravatar.cc/150?img=45",
		is_following: true,
	},
	{
		id: 16,
		username: "basshunter",
		first_name: "Noah",
		last_name: "Fischer",
		avatar: "https://i.pravatar.cc/150?img=53",
		is_following: false,
	},
	{
		id: 17,
		username: "pop_diva",
		first_name: "Emily",
		last_name: "Taylor",
		avatar: "https://i.pravatar.cc/150?img=11",
		is_following: true,
	},
	{
		id: 18,
		username: "groove_king",
		first_name: "Carlos",
		last_name: "Santos",
		avatar: "https://i.pravatar.cc/150?img=31", // corrigé: ajout d'un img=
		is_following: true,
	},
	{
		id: 19,
		username: "lofi_cat",
		first_name: "Mila",
		last_name: "Klein",
		avatar: "https://i.pravatar.cc/150?img=13",
		is_following: false,
	},
	{
		id: 20,
		username: "deep_house",
		first_name: "Omar",
		last_name: "Rahman",
		avatar: "https://i.pravatar.cc/150?img=61",
		is_following: true,
	},
	{
		id: 21,
		username: "strings_attached",
		first_name: "Jules",
		last_name: "Moreau",
		avatar: "https://i.pravatar.cc/150?img=25",
		is_following: false,
	},
	{
		id: 22,
		username: "ukulele_vibes",
		first_name: "Lea",
		last_name: "Martins",
		avatar: "https://i.pravatar.cc/150?img=28",
		is_following: true,
	},
	{
		id: 23,
		username: "synthwave_dad",
		first_name: "Patrick",
		last_name: "O'Connor",
		avatar: "https://i.pravatar.cc/150?img=52",
		is_following: false,
	},
	{
		id: 24,
		username: "bossa_nova",
		first_name: "Fernanda",
		last_name: "Silva",
		avatar: "https://i.pravatar.cc/150?img=63",
		is_following: true,
	},
	{
		id: 25,
		username: "metal_core",
		first_name: "Viktor",
		last_name: "Ivanov",
		avatar: "https://i.pravatar.cc/150?img=44",
		is_following: false,
	},
	{
		id: 26,
		username: "trap_lord",
		first_name: "Aisha",
		last_name: "Khan",
		avatar: "https://i.pravatar.cc/150?img=20",
		is_following: true,
	},
	{
		id: 27,
		username: "indie_coffee",
		first_name: "Hugo",
		last_name: "Rossi",
		avatar: "https://i.pravatar.cc/150?img=10",
		is_following: false,
	},
	{
		id: 28,
		username: "vinyl_addict",
		first_name: "Sanaa",
		last_name: "Benali",
		avatar: "https://i.pravatar.cc/150?img=49",
		is_following: true,
	},
	{
		id: 29,
		username: "folk_tales",
		first_name: "Nora",
		last_name: "Larsen",
		avatar: "https://i.pravatar.cc/150?img=27",
		is_following: false,
	},
	{
		id: 30,
		username: "808wizard",
		first_name: "Zach",
		last_name: "Carter",
		avatar: "https://i.pravatar.cc/150?img=33",
		is_following: true,
	},
	{
		id: 31,
		username: "piano_bar",
		first_name: "Elena",
		last_name: "Ionescu",
		avatar: "https://i.pravatar.cc/150?img=26",
		is_following: false,
	},
	{
		id: 32,
		username: "drum_machine",
		first_name: "Yuki",
		last_name: "Sato",
		avatar: "https://i.pravatar.cc/150?img=60",
		is_following: true,
	},
	{
		id: 33,
		username: "garage_band",
		first_name: "Lucas",
		last_name: "Fernandez",
		avatar: "https://i.pravatar.cc/150?img=6",
		is_following: false,
	},
	{
		id: 34,
		username: "opera_lover",
		first_name: "Clara",
		last_name: "Moretti",
		avatar: "https://i.pravatar.cc/150?img=21",
		is_following: true,
	},
	{
		id: 35,
		username: "ambient_air",
		first_name: "Sven",
		last_name: "Eriksen",
		avatar: "https://i.pravatar.cc/150?img=31",
		is_following: false,
	},
	{
		id: 36,
		username: "rnb_addict",
		first_name: "Keisha",
		last_name: "Brooks",
		avatar: "https://i.pravatar.cc/150?img=62",
		is_following: true,
	},
	{
		id: 37,
		username: "ska_skank",
		first_name: "Mateo",
		last_name: "Gonzalez",
		avatar: "https://i.pravatar.cc/150?img=40",
		is_following: false,
	},
	{
		id: 38,
		username: "kpop_star",
		first_name: "Minji",
		last_name: "Park",
		avatar: "https://i.pravatar.cc/150?img=16",
		is_following: true,
	},
	{
		id: 39,
		username: "afrobeat_wave",
		first_name: "Kwame",
		last_name: "Mensah",
		avatar: "https://i.pravatar.cc/150?img=57",
		is_following: false,
	},
	{
		id: 40,
		username: "blues_harp",
		first_name: "Grace",
		last_name: "Allen",
		avatar: "https://i.pravatar.cc/150?img=8",
		is_following: true,
	},
	{
		id: 41,
		username: "edm_freak",
		first_name: "Rita",
		last_name: "Novak",
		avatar: "https://i.pravatar.cc/150?img=23",
		is_following: false,
	},
	{
		id: 42,
		username: "grime_time",
		first_name: "Luca",
		last_name: "Bianchi",
		avatar: "https://i.pravatar.cc/150?img=55",
		is_following: true,
	},
	{
		id: 43,
		username: "jpop_karaoke",
		first_name: "Haruto",
		last_name: "Tanaka",
		avatar: "https://i.pravatar.cc/150?img=5",
		is_following: false,
	},
	{
		id: 44,
		username: "latin_heat",
		first_name: "Camila",
		last_name: "Ruiz",
		avatar: "https://i.pravatar.cc/150?img=19",
		is_following: true,
	},
	{
		id: 45,
		username: "new_wave",
		first_name: "Iris",
		last_name: "Chan",
		avatar: "https://i.pravatar.cc/150?img=15",
		is_following: false,
	},
	{
		id: 46,
		username: "psy_trance",
		first_name: "Arjun",
		last_name: "Patel",
		avatar: "https://i.pravatar.cc/150?img=34",
		is_following: true,
	},
	{
		id: 47,
		username: "reggae_roots",
		first_name: "Jamal",
		last_name: "King",
		avatar: "https://i.pravatar.cc/150?img=30",
		is_following: false,
	},
	{
		id: 48,
		username: "shoegaze_sun",
		first_name: "Eva",
		last_name: "Müller",
		avatar: "https://i.pravatar.cc/150?img=59",
		is_following: true,
	},
	{
		id: 49,
		username: "swing_step",
		first_name: "Oliver",
		last_name: "Bennett",
		avatar: "https://i.pravatar.cc/150?img=37",
		is_following: false,
	},
	{
		id: 50,
		username: "vocal_chops",
		first_name: "Ariana",
		last_name: "Costa",
		avatar: "https://i.pravatar.cc/150?img=35",
		is_following: true,
	},
];
