import type { INotificationsResponse } from "@/types/profile/notifications/notification.types";

export const mock_notifications_response: INotificationsResponse = {
	notifications: [
		// --- New notifications (unread) ---
		{
			id: 1,
			recipient_id: 1,
			sender_id: 101,
			sender_username: "dj_shadow",
			preview_image: "https://picsum.photos/seed/lofi1/300/200",
			target_type: "post_like",
			target_id: 1,
			is_read: false,
			created_at: "2025-11-14T10:10:00Z",
		},
		{
			id: 2,
			recipient_id: 1,
			sender_id: 102,
			sender_username: "lofi_girl",
			preview_image: "https://i.pravatar.cc/150?img=32",
			target_type: "post_comment",
			target_id: 2,
			content: "Perfect for studying ✨",
			is_read: false,
			created_at: "2025-11-13T13:42:00Z",
		},
		{
			id: 6,
			recipient_id: 1,
			sender_id: 106,
			sender_username: "beatmakerX",
			preview_image: "https://i.pravatar.cc/150?img=15",
			target_type: "message",
			target_id: 0,
			content: "Check out my new beat 🔥",
			is_read: false,
			created_at: "2025-11-02T12:10:00Z",
		},
		{
			id: 7,
			recipient_id: 1,
			sender_id: 107,
			sender_username: "vinyl_lover",
			preview_image: "https://picsum.photos/seed/vinyl/300/200",
			target_type: "post_like",
			target_id: 2,
			is_read: false,
			created_at: "2025-10-02T11:50:00Z",
		},
		{
			id: 8,
			recipient_id: 1,
			sender_id: 108,
			sender_username: "jane_doe",
			preview_image: "https://i.pravatar.cc/150?img=47",
			target_type: "follow",
			target_id: 0,
			is_read: false,
			created_at: "2025-10-02T10:30:00Z",
		},

		// --- Old notifications (read) ---
		{
			id: 3,
			recipient_id: 1,
			sender_id: 103,
			sender_username: "rockfan92",
			preview_image: "https://picsum.photos/seed/follow/300/200",
			target_type: "follow",
			target_id: 0,
			is_read: true,
			created_at: "2025-09-01T20:05:00Z",
		},
		{
			id: 4,
			recipient_id: 1,
			sender_id: 104,
			sender_username: "trapqueen",
			preview_image: "https://picsum.photos/seed/msg/300/200",
			target_type: "message",
			target_id: 0,
			content: "Wanna collab this weekend?",
			is_read: true,
			created_at: "2025-08-31T09:15:00Z",
		},
		{
			id: 5,
			recipient_id: 1,
			sender_id: 105,
			sender_username: "jazzman",
			preview_image: "https://picsum.photos/seed/jazz/300/200",
			target_type: "post_comment",
			target_id: 2,
			content: "Love the vibe 🎷",
			is_read: true,
			created_at: "2025-08-30T18:45:00Z",
		},
		{
			id: 9,
			recipient_id: 1,
			sender_id: 109,
			sender_username: "house_master",
			preview_image: "https://picsum.photos/seed/house/300/200",
			target_type: "post_like",
			target_id: 1,
			is_read: true,
			created_at: "2025-08-29T21:10:00Z",
		},
		{
			id: 10,
			recipient_id: 1,
			sender_id: 110,
			sender_username: "electro_queen",
			preview_image: "https://i.pravatar.cc/150?img=56",
			target_type: "follow",
			target_id: 0,
			is_read: true,
			created_at: "2025-08-28T15:25:00Z",
		},
	],
	total_notifications: 10,
	unread_count: 5,
};
